
package org.com.cay.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EpServiceImplService", targetNamespace = "http://impl.webservice.cay.com.org/", wsdlLocation = "http://localhost:8080/business_export_server/ws/export?wsdl")
public class EpServiceImplService
    extends Service
{

    private final static URL EPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EPSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.cay.com.org/", "EpServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/business_export_server/ws/export?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public EpServiceImplService() {
        super(__getWsdlLocation(), EPSERVICEIMPLSERVICE_QNAME);
    }

    public EpServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPSERVICEIMPLSERVICE_QNAME, features);
    }

    public EpServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EPSERVICEIMPLSERVICE_QNAME);
    }

    public EpServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPSERVICEIMPLSERVICE_QNAME, features);
    }

    public EpServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEpService
     */
    @WebEndpoint(name = "EpServiceImplPort")
    public IEpService getEpServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.cay.com.org/", "EpServiceImplPort"), IEpService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEpService
     */
    @WebEndpoint(name = "EpServiceImplPort")
    public IEpService getEpServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.cay.com.org/", "EpServiceImplPort"), IEpService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return EPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
