
package org.com.cay.webservice.impl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://webservice.cay.com.org/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.com.cay.webservice.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception(String message, org.com.cay.webservice.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception(String message, org.com.cay.webservice.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.com.cay.webservice.Exception
     */
    public org.com.cay.webservice.Exception getFaultInfo() {
        return faultInfo;
    }

}
