
package org.com.cay.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExportWebServiceImplService", targetNamespace = "http://impl.webservice.cay.com.org/", wsdlLocation = "http://localhost:8080/business_export_server/ws/export?wsdl")
public class ExportWebServiceImplService
    extends Service
{

    private final static URL EXPORTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPORTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName EXPORTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.cay.com.org/", "ExportWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/business_export_server/ws/export?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPORTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        EXPORTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ExportWebServiceImplService() {
        super(__getWsdlLocation(), EXPORTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ExportWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPORTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ExportWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, EXPORTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ExportWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPORTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ExportWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExportWebService
     */
    @WebEndpoint(name = "ExportWebServiceImplPort")
    public IExportWebService getExportWebServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.cay.com.org/", "ExportWebServiceImplPort"), IExportWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExportWebService
     */
    @WebEndpoint(name = "ExportWebServiceImplPort")
    public IExportWebService getExportWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.cay.com.org/", "ExportWebServiceImplPort"), IExportWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPORTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw EXPORTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return EXPORTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
